caratteri: main.o listaCaratteri.o
	gcc main.o listaCaratteri.o -o ./caratteri

main: main.c listaCaratteri.h
	gcc -c main.c

listaCaratteri: listaCaratteri.c listaCaratteri.h
	gcc -c listaCaratteri.c